[options]
db_host = localhost
db_name = 18-fadhel-latest
db_user = odoo
db_password = odoo
dbfilter = ^18-fadhel-
db_port = 5432
without_demo = all
xmlrpc_port = 8088
addons_path = C:\odoo\odoo18\odoo\odoo\addons\base,C:\odoo\odoo18\odoo\addons,C:\odoo\odoo18\enterprise,C:\odoo\odoo18\fadhel-addons,C:\odoo\odoo18\web
bin_path = C:\Program Files\wkhtmltopdf\bin
webkit_path = C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe
max_cron_threads = 0
admin_passwd = $pbkdf2-sha512$600000$.n8PIUTo3bu3FuJcy9l77w$ecs.PUiEviMV.aRdpcPaH.rxxsg7KI5peaxYVKBGm1x2xl3xLzJLfqOiRoSwTKXHJ3mHLCT.y2JASoxByMBoyw
;5rfq-g3eb-gkgf