[options]
db_host = localhost
db_name = 18-ecommerce
db_user = odoo
db_password = odoo
dbfilter = ^18-ecommerce
db_port = 5432
;without_demo = all
xmlrpc_port = 8069
addons_path = /Users/fadhelalqaidoom/Desktop/odoo/odoo18/odoo/odoo/addons/base,/Users/fadhelalqaidoom/Desktop/odoo/odoo18/odoo/addons,/Users/fadhelalqaidoom/Desktop/odoo/odoo18/enterprise,/Users/fadhelalqaidoom/Desktop/e-commerce/e-commerce
max_cron_threads = 0
admin_passwd = $pbkdf2-sha512$600000$.n8PIUTo3bu3FuJcy9l77w$ecs.PUiEviMV.aRdpcPaH.rxxsg7KI5peaxYVKBGm1x2xl3xLzJLfqOiRoSwTKXHJ3mHLCT.y2JASoxByMBoyw
;5rfq-g3eb-gkgf